version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.16.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:ci
      - store_test_results: 
          path: ./junit.xml

  deploy:
    docker:
      - image: cimg/node:18.16.0

    steps:
      - add_ssh_keys:
          fingerprints:
            - "7f:5d:57:ff:65:3c:c0:c5:2f:32:a2:6e:80:a0:3c:ba"
      - checkout
      - run:
          name: Push Staging to Production
          command: |
            git push https://github.com/jbuistjbuist/portfolio_website_.git staging:production

workflows:
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging
      - deploy:
          filters:
            branches:
              only: staging
          requires:
            - build
