version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:10.18

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test:ci

  deploy:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "01:97:64:92:b9:f4:d4:ee:62:93:16:e8:98:03:f2:cd"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/jbuistjbuist/portfolio_website_.git staging:production

workflows:
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build